# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hyperion}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["adrianpike"]
  s.date = %q{2010-12-22}
  s.description = %q{Hyperion is a sweet Ruby data model thats backed with Redis. It's designed to be screamin' fast.}
  s.email = %q{adrian.pike@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "CHANGELOG",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "benchmarks.rb",
    "hyperion.gemspec",
    "lib/hyperion.rb",
    "lib/hyperion/base.rb",
    "lib/hyperion/finders.rb",
    "lib/hyperion/hyperion_active_model.rb",
    "lib/hyperion/indices.rb",
    "lib/hyperion/keys.rb",
    "lib/hyperion/logger.rb",
    "lib/hyperion/sharding.rb",
    "lib/hyperion/version.rb",
    "spec/callbacks_spec.rb",
    "spec/finders_spec.rb",
    "spec/hyperion_spec.rb",
    "spec/indices_spec.rb",
    "spec/lint_test.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/adrianpike/hyperion}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Hyperion is a sweet Ruby data model thats backed with Redis.}
  s.test_files = [
    "spec/callbacks_spec.rb",
    "spec/finders_spec.rb",
    "spec/hyperion_spec.rb",
    "spec/indices_spec.rb",
    "spec/lint_test.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<activemodel>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<activemodel>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<activemodel>, [">= 0"])
  end
end

