# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hyperion}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["adrianpike"]
  s.date = %q{2010-10-28}
  s.description = %q{Hyperion is a sweet Ruby data model thats backed with Redis. It's designed to be screamin' fast.}
  s.email = %q{adrian.pike@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "benchmarks.rb",
     "lib/hyperion.rb",
     "lib/hyperion/base.rb",
     "lib/hyperion/finders.rb",
     "lib/hyperion/indices.rb",
     "lib/hyperion/keys.rb",
     "lib/hyperion/logger.rb",
     "lib/hyperion/version.rb",
     "spec/hyperion_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/adrianpike/hyperion}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Hyperion is a sweet Ruby data model thats backed with Redis.}
  s.test_files = [
    "spec/hyperion_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

